name: 'Build and Run Example'
description: 'Configure, build, and run metagraph example'

inputs:
  example-type:
    description: 'Type of example (subdirectory or ExternalProject)'
    required: true
  build-type:
    description: 'CMake build type (Debug or Release)'
    required: true
  alphabet:
    description: 'Alphabet type (DNA or Protein)'
    required: true
  build-static:
    description: 'Build static binaries (ON or OFF)'
    required: false
    default: 'OFF'
  with-avx:
    description: 'Enable AVX instructions (ON or OFF)'
    required: false
    default: 'ON'
  git-tag:
    description: 'Git tag for ExternalProject (only used if example-type is ExternalProject)'
    required: false
    default: ''
  target-arch:
    description: 'Target architecture (arm64 or x86_64, macOS only)'
    required: false
    default: 'arm64'

runs:
  using: 'composite'
  steps:
    - name: Setup ccache
      if: ${{ runner.os == 'macOS' }}
      uses: ./.github/actions/setup-ccache
      with:
        build-type: ${{ inputs.build-type }}
        alphabet: ${{ inputs.alphabet }}
        build-static: ${{ inputs.build-static }}
        with-avx: ${{ inputs.with-avx }}
        target-arch: ${{ inputs.target-arch }}
        job-type: ${{ inputs.example-type }}

    - name: Configure example
      run: |
        cd metagraph-examples/${{ inputs.example-type }}
        mkdir -p build && cd build
        if [ "${{ inputs.example-type }}" = "subdirectory" ]; then
          cmake -DCMAKE_BUILD_TYPE=${{ inputs.build-type }} \
                ${BUILD_STATIC:+-DBUILD_STATIC=$BUILD_STATIC} \
                ${WITH_AVX:+-DWITH_AVX=$WITH_AVX -DWITH_MSSE42=$WITH_AVX} \
                -DCMAKE_DBG_ALPHABET=${{ inputs.alphabet }} ..
        else
          cmake -DCMAKE_BUILD_TYPE=${{ inputs.build-type }} \
                -DMETAGRAPH_GIT_TAG=${{ inputs.git-tag }} \
                ${BUILD_STATIC:+-DBUILD_STATIC=$BUILD_STATIC} \
                ${WITH_AVX:+-DWITH_AVX=$WITH_AVX -DWITH_MSSE42=$WITH_AVX} \
                -DCMAKE_DBG_ALPHABET=${{ inputs.alphabet }} ..
        fi
      env:
        BUILD_STATIC: ${{ inputs.build-static != 'OFF' && inputs.build-static || '' }}
        WITH_AVX: ${{ inputs.with-avx != 'ON' && inputs.with-avx || '' }}
      shell: ${{ runner.os == 'macOS' && format('arch -{0} /bin/bash -e {{0}}', inputs.target-arch) || 'bash' }}

    - name: Build example
      run: cd metagraph-examples/${{ inputs.example-type }}/build && make -j"$(getconf _NPROCESSORS_ONLN)"
      shell: ${{ runner.os == 'macOS' && format('arch -{0} /bin/bash -e {{0}}', inputs.target-arch) || 'bash' }}

    - name: Run example
      run: |
        cd metagraph-examples/${{ inputs.example-type }}/build
        make run_example
      shell: ${{ runner.os == 'macOS' && format('arch -{0} /bin/bash -e {{0}}', inputs.target-arch) || 'bash' }}

    - name: Show ccache statistics
      run: ccache --show-stats
      shell: bash
