name: 'Checkout with Submodules'
description: 'Checkout repository with cached submodules'

inputs:
  fetch-depth:
    description: 'Number of commits to fetch. 0 for all history, 1 for shallow clone'
    required: false
    default: '1'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: ${{ inputs.fetch-depth }}

    - name: Cache submodules
      uses: actions/cache@v3
      with:
        path: |
          .git/modules
          metagraph/external-libraries
        key: submodules-${{ hashFiles('.gitmodules') }}
        restore-keys: |
          submodules-
      shell: bash

    - name: Checkout submodules
      run: git submodule update --init --recursive --depth 1
      shell: bash
