name: 'Build Metagraph'
description: 'Configure and build metagraph with all targets'

inputs:
  build-type:
    description: 'CMake build type (Debug or Release)'
    required: true
  alphabet:
    description: 'Alphabet type (DNA or Protein)'
    required: true
  build-static:
    description: 'Build static binaries (ON or OFF)'
    required: false
    default: 'OFF'
  with-avx:
    description: 'Enable AVX instructions (ON or OFF)'
    required: false
    default: 'ON'
  build-unit-tests:
    description: 'Whether to build unit tests'
    required: false
    default: 'true'
  target-arch:
    description: 'Target architecture (arm64 or x86_64, macOS only)'
    required: false
    default: 'arm64'

runs:
  using: 'composite'
  steps:
    - name: Setup ccache
      uses: ./.github/actions/setup-ccache
      with:
        build-type: ${{ inputs.build-type }}
        alphabet: ${{ inputs.alphabet }}
        build-static: ${{ inputs.build-static }}
        with-avx: ${{ inputs.with-avx }}
        target-arch: ${{ inputs.target-arch }}

    - name: Configure
      run: |
        mkdir -p metagraph/build
        cd metagraph/build
        cmake -DCMAKE_BUILD_TYPE=${{ inputs.build-type }} \
              ${BUILD_STATIC:+-DBUILD_STATIC=$BUILD_STATIC} \
              ${WITH_AVX:+-DWITH_AVX=$WITH_AVX -DWITH_MSSE42=$WITH_AVX} \
              -DCMAKE_DBG_ALPHABET=${{ inputs.alphabet }} ..
      env:
        BUILD_STATIC: ${{ inputs.build-static != 'OFF' && inputs.build-static || '' }}
        WITH_AVX: ${{ inputs.with-avx != 'ON' && inputs.with-avx || '' }}
      shell: arch -${{ inputs.target-arch }} /bin/bash -e {0}

    - name: Build metagraph
      run: cd metagraph/build && make -j"$(getconf _NPROCESSORS_ONLN)" metagraph
      shell: arch -${{ inputs.target-arch }} /bin/bash -e {0}

    - name: Build unit tests
      if: inputs.build-unit-tests == 'true'
      run: cd metagraph/build && make -j"$(getconf _NPROCESSORS_ONLN)" unit_tests
      shell: arch -${{ inputs.target-arch }} /bin/bash -e {0}

    - name: Build other
      run: cd metagraph/build && make -j"$(getconf _NPROCESSORS_ONLN)"
      shell: arch -${{ inputs.target-arch }} /bin/bash -e {0}

    - name: Show ccache statistics
      run: ccache --show-stats
      shell: bash
