FROM ubuntu:20.04

RUN export DEBIAN_FRONTEND="noninteractive" && apt-get update && apt-get install -y \
    autoconf \
    automake \
    binutils-dev \
    ccache \
    cmake \
    curl \
    extra-cmake-modules \
    g++-9 \
    git \
    libboost-all-dev \
    libbrotli-dev \
    libbz2-dev \
    libdouble-conversion-dev \
    libevent-dev \
    libgflags-dev \
    libgoogle-glog-dev \
    libiberty-dev \
    libjemalloc-dev \
    liblz4-dev \
    liblzma-dev \
    libsnappy-dev \
    libssl-dev \
    libtool \
    libunwind-dev \
    make \
    pkg-config \
    python3 \
    python3-pip \
    python3-venv \
    vim \
    wget \
    zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install parameterized==0.7.1

WORKDIR /opt
ENV LD_LIBRARY_PATH=/usr/local/lib
ENV CC /usr/bin/gcc-9
ENV CXX /usr/bin/g++-9

### Compile our own libcurl (the apt package creates issueswith static builds
RUN git clone https://github.com/curl/curl.git && mkdir curl/_build && cd curl/_build && cmake -DBUILD_SHARED_LIBS=on .. && make -j $(nproc) && make install && cmake -DBUILD_SHARED_LIBS=off .. && make -j $(nproc) && make install && cd /opt && rm -rf curl

### Installing htslib

ARG HTSLIB_VERSION=1.10.2
RUN wget https://github.com/samtools/htslib/releases/download/$HTSLIB_VERSION/htslib-$HTSLIB_VERSION.tar.bz2 && tar -vxjf htslib-$HTSLIB_VERSION.tar.bz2 && cd htslib-$HTSLIB_VERSION && make -j $(nproc) && make install && cd /opt && rm -rf htslib-$HTSLIB_VERSION

### Setting up fmt (dependency of folly)
RUN git clone https://github.com/fmtlib/fmt.git && cd fmt && mkdir _build && cd _build && cmake .. && make -j$(nproc) && make install && cd /opt && rm -rf fmt

## Setting up folly
RUN git clone https://github.com/facebook/folly.git && cd folly && mkdir _build && cd _build && cmake .. && make -j $(nproc) && make install && cd /opt && rm -rf folly

RUN mkdir -p /opt/metagraph/build_docker
RUN chmod o+rwx /opt/metagraph

ENV CCACHE_DIR=/opt/metagraph/build/ccache_docker
