name: 'Install macOS Dependencies'
description: 'Install dependencies for building and testing MetaGraph on macOS'

inputs:
  install_test_deps:
    description: 'Whether to install integration test dependencies'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: install build dependencies
      shell: bash
      run: brew install bzip2 libomp boost jemalloc autoconf automake libdeflate icu4c zstd

    - name: install dependencies for integration tests
      if: inputs.install_test_deps == 'true'
      shell: bash
      run: pip3 install parameterized --break-system-packages --user
