name: 'Checkout Submodules with Cache'
description: 'Checkout submodules with caching (requires repository already checked out)'

runs:
  using: 'composite'
  steps:
    - name: Cache submodules
      uses: actions/cache@v3
      with:
        path: |
          .git/modules
          metagraph/external-libraries
        key: submodules-${{ hashFiles('.gitmodules') }}

    - name: Checkout submodules
      run: git submodule update --init --recursive --depth 1
      shell: bash
