from pathlib import Path

import metagraph_workflows.utils
from metagraph_workflows import workflow_configs, utils
from metagraph_workflows.utils import take_value_or_default
from metagraph_workflows.workflow_configs import AnnotationLabelsSource, \
    AnnotationFormats
from metagraph_workflows.resource_management import TransformRdStage0Resources, TransformRdStage1Resources, TransformRdStage2Resources, AnnotateResources, ResourceConfig

wdir=utils.get_wdir(config)

graph=config['base_name']
build_primary=config['build_primary_graph']

annotation_formats = config['annotation_formats'] if isinstance(config['annotation_formats'], list) else [config['annotation_formats']]

# validate values
for af in annotation_formats:
    AnnotationFormats(af)
    # TODO: make a nicer error

annotation_labels_opt = AnnotationLabelsSource(config['annotation_labels_source']).to_annotation_cmd_option()
with_counts = config[workflow_configs.WITH_COUNTS]
with_coordinates = config[workflow_configs.WITH_COORDINATES]
if with_counts and with_coordinates:
    raise RuntimeError(
        'with_counts and with_coordinates cannot both be true (same constraint as metagraph row-diff).')
count_width = config[workflow_configs.COUNT_WIDTH]
count_kmers_opt = '--count-kmers' if with_counts else ''
coordinates_opt = '--coordinates' if with_coordinates else ''
count_width_opt = f'--count-width {count_width}' if with_counts else ''


metagraph_cmd=config['metagraph_cmd']
time_cmd=utils.get_gnu_time_command(config)

max_threads=take_value_or_default(workflow_configs.MAX_THREADS, workflow.cores, config)

verbose_opt=' -v '

DONE="DONE"

## Paths
graph_path=wdir/f'{graph}.dbg'
if with_counts:
    annotation_mode_suffix = f'counts.w{count_width}'
elif with_coordinates:
    annotation_mode_suffix = 'coords'
else:
    annotation_mode_suffix = 'binary'
annotation_cols_path=wdir/f'columns.{annotation_mode_suffix}'
annotation_path_done=annotation_cols_path/DONE

columns_file=wdir/f'columns.{annotation_mode_suffix}.txt'

seqs_file_list_path=utils.get_seqs_file_list_path(wdir, config)

column_anno_paths = utils.generate_col_paths(annotation_cols_path, seqs_file_list_path, config)
column_counts_paths = [Path(str(p) + '.counts') for p in column_anno_paths] if with_counts else []
column_coords_paths = [Path(str(p) + '.coords') for p in column_anno_paths] if with_coordinates else []

contigs_dir=wdir/'contigs'

seq_ids_dict = {}
if not config[workflow_configs.SAMPLE_IDS_PATH]:
    seq_ids_dict = utils.derive_sample_dictionary(seqs_file_list_path)

localrules: generate_column_list

rule all:
    input:
        graph_path,
        [wdir/f'{graph}.{anno_type}.annodbg' for anno_type in annotation_formats]


include: 'build.smk'

ANNOTATE_RULE="annotate"
rule annotate:
    input:
        seqs=utils.get_build_joint_input(config, contigs_dir, seq_ids_dict, seqs_file_list_path),
        dbg_graph=graph_path,
    output:
        done=touch(annotation_path_done),
        column_anno_files=temp(column_anno_paths),
        column_count_files=(temp(column_counts_paths) if with_counts else []),
        column_coord_files=(temp(column_coords_paths) if with_coordinates else []),
    threads: max_threads
    resources:
        mem_mb=ResourceConfig(ANNOTATE_RULE, config).get_mem(),
    params:
        separate_build=str(bool(config[workflow_configs.PRIMARIZE_SAMPLES_SEPARATELY])).lower(),
        tempdir_opt=utils.temp_dir_config(config),
        threads_each=lambda wildcards, threads: AnnotateResources(config).get_effective_threads_each(threads),
        parallel_cols=lambda wildcards, threads: AnnotateResources(config).get_parallel_cols(threads),
        mem_buffer=AnnotateResources(config).get_mem_buffer_gib(),
    log: utils.get_log_path(ANNOTATE_RULE, config)
    shell:
        """
        if {params.separate_build}; then
            SEQ_PATHS={wdir}/seqs_paths.txt
            echo "{input}" | tr ' ' '\n' > $SEQ_PATHS
        else
            SEQ_PATHS="{input.seqs}"
        fi

        OUT_DIR=$(dirname {output.done})
        mkdir -p $OUT_DIR
        cat $SEQ_PATHS | {time_cmd} {metagraph_cmd} annotate \
          {verbose_opt} \
          --parallel {params.parallel_cols} \
          --threads-each {params.threads_each} \
          --mem-cap-gb {params.mem_buffer} \
          -i {input.dbg_graph} \
          {annotation_labels_opt} \
          {count_kmers_opt} \
          {coordinates_opt} \
          {count_width_opt} \
          --anno-type column \
          --separately \
          -o $OUT_DIR {params.tempdir_opt} > {log} 2>&1
        """

GENERATE_COLUMN_LIST_RULE="generate_column_list"
rule generate_column_list:
    input: rules.annotate.output.column_anno_files
    output: temp(columns_file)
    run:
        with open(output[0], 'w') as f:
            f.write('\n'.join([str(l) for l in input]))


max_path_length=None

GENERATE_BRWT_LINKAGE_RULE="generate_brwt_linkage"
rule generate_brwt_linkage:
    input:
        columns_file=columns_file,
        column_anno_files=rules.annotate.output.column_anno_files,
        column_count_files=rules.annotate.output.column_count_files,
        column_coord_files=rules.annotate.output.column_coord_files,
    output:
        linkage=wdir/f"{graph}.linkage.txt"
    threads: max_threads
    resources:
        mem_mb=ResourceConfig(GENERATE_BRWT_LINKAGE_RULE, config).get_mem(),
    params:
        subsample=config[workflow_configs.BRWT_LINKAGE_SUBSAMPLE],
    log: utils.get_log_path(GENERATE_BRWT_LINKAGE_RULE, config)
    shell:
        """        
        cat {input.columns_file} | {time_cmd} {metagraph_cmd} transform_anno {verbose_opt} \
            --anno-type brwt \
            --linkage \
            --greedy \
            --subsample {params.subsample} \
            --parallel {threads} \
            -o {output.linkage} > {log} 2>&1
        """

ruleorder: relax_brwt > transform_annotation # more specific rule has priority
ruleorder: annotate_row_diff_brwt > transform_annotation
ruleorder: annotate_row_diff_int_brwt > transform_annotation
ruleorder: annotate_row_diff_int_disk > transform_annotation
ruleorder: annotate_row_diff_brwt_coord > transform_annotation
ruleorder: annotate_row_diff_coord > transform_annotation
ruleorder: annotate_row_diff_disk_coord > transform_annotation

TRANSFORM_ANNOTATION_RULE="transform_annotation"
rule transform_annotation:
    input:
        columns_file=columns_file,
        column_anno_files=rules.annotate.output.column_anno_files,
        column_count_files=rules.annotate.output.column_count_files,
        column_coord_files=rules.annotate.output.column_coord_files,
    output:
        annotations=wdir/f'{graph}.{{anno_type}}.annodbg',
    threads: max_threads
    resources:
        mem_mb=ResourceConfig(TRANSFORM_ANNOTATION_RULE, config).get_mem(),
    params:
        tempdir_opt=utils.temp_dir_config(config),
    log: utils.get_log_path(TRANSFORM_ANNOTATION_RULE, config, ['anno_type'])
    shell:
        """        
        cat {input.columns_file} | {time_cmd} {metagraph_cmd} transform_anno {verbose_opt} \
            --anno-type {wildcards.anno_type} \
            --parallel {threads} \
            -o {output.annotations} {params.tempdir_opt} > {log} 2>&1
        """


ANNOTATE_BRWT_RULE="annotate_brwt"
rule annotate_brwt:
    input:
        linkage=wdir/f"{graph}.linkage.txt",
        columns_file=columns_file,
        column_anno_files=rules.annotate.output.column_anno_files,
        column_count_files=rules.annotate.output.column_count_files,
        column_coord_files=rules.annotate.output.column_coord_files,
    output:
        annotations=wdir/f'{graph}.brwt.annodbg',
    threads: max_threads
    resources:
        mem_mb=ResourceConfig(ANNOTATE_BRWT_RULE, config).get_mem(),
    params:
        parallel_nodes=config[workflow_configs.BRWT_PARALLEL_NODES],
        tempdir_opt=utils.temp_dir_config(config),
    log: utils.get_log_path(ANNOTATE_BRWT_RULE, config)
    shell:
        """        
        cat {input.columns_file} | {time_cmd} {metagraph_cmd} transform_anno {verbose_opt} \
            --anno-type brwt \
            --parallel-nodes {params.parallel_nodes} \
            --greedy \
            --parallel {threads} \
            -o {output.annotations} {params.tempdir_opt} > {log} 2>&1
        """


RELAX_BRWT_RULE="relax_brwt"
rule relax_brwt:
    input:
        brwt_annots=wdir/f'{graph}.{{brwt_fmt}}.annodbg',
    output:
        annotations=wdir/f'{graph}.relax.{{brwt_fmt}}.annodbg',
    threads: max_threads
    resources:
        mem_mb=ResourceConfig(RELAX_BRWT_RULE, config).get_mem(),
    params:
        relax_arity=config[workflow_configs.BRWT_RELAX_ARITY],
    log: utils.get_log_path(RELAX_BRWT_RULE, config, ['brwt_fmt'])
    shell:
        """
        {time_cmd} {metagraph_cmd} relax_brwt \
            -o {output.annotations} \
            {verbose_opt} \
            --relax-arity {params.relax_arity} \
            --parallel {threads} \
            {input.brwt_annots} > {log} 2>&1
        """

rd_cols_dir = wdir/f'rd_cols.{annotation_mode_suffix}'

# Stage 2: *.column.annodbg (counts/coords) vs *.row_diff.annodbg (binary row-diff only).
rd_col_annodbg_suffix = '.column.annodbg' if (with_counts or with_coordinates) else '.row_diff.annodbg'
rd_col_annodbg_paths = utils.generate_col_paths(rd_cols_dir, seqs_file_list_path, config, suffix=rd_col_annodbg_suffix)
rd_col_counts_paths = [Path(str(p) + '.counts') for p in rd_col_annodbg_paths] if with_counts else []
rd_col_coords_paths = [Path(str(p) + '.coords') for p in rd_col_annodbg_paths] if with_coordinates else []

from metagraph_workflows.resource_management import TransformRdStage0Resources

TRANSFORM_RD_STAGE0_RULE="transform_rd_stage0"
rule transform_rd_stage0:
    input:
        dbg_graph=graph_path,
        columns_file=columns_file,
        column_anno_files=rules.annotate.output.column_anno_files,
        column_count_files=rules.annotate.output.column_count_files,
        column_coord_files=rules.annotate.output.column_coord_files,
    output:
        columns_rd_row_count=temp(rd_cols_dir/'vector.row_count')
    threads: max_threads
    resources:
        mem_mb=TransformRdStage0Resources(config).get_mem()
    params:
        mem_buffer=TransformRdStage0Resources(config).get_mem_buffer_gib(),
        tempdir_opt=utils.temp_dir_config(config),
    log: utils.get_log_path(TRANSFORM_RD_STAGE0_RULE,config)
    shell:
        """
        COLS_DIR=$(dirname {output.columns_rd_row_count})
        mkdir -p $COLS_DIR
        
        cat {input.columns_file} | {time_cmd} {metagraph_cmd} transform_anno {verbose_opt} \
            --anno-type row_diff \
            --row-diff-stage 0 \
            -i {input.dbg_graph} \
            --parallel {threads} \
            {count_kmers_opt} \
            {coordinates_opt} \
            {count_width_opt} \
            --mem-cap-gb {params.mem_buffer} \
            -o {output.columns_rd_row_count} {params.tempdir_opt} > {log} 2>&1
        """

TRANSFORM_RD_STAGE1_RULE="transform_rd_stage1"
rule transform_rd_stage1:
    input:
        dbg_graph=graph_path,
        columns_file=columns_file,
        column_anno_files=rules.annotate.output.column_anno_files,
        column_count_files=rules.annotate.output.column_count_files,
        column_coord_files=rules.annotate.output.column_coord_files,
        columns_rd_row_count=rules.transform_rd_stage0.output.columns_rd_row_count
    output:
        pred=temp(wdir / f'{graph}.dbg.pred'),
        pred_boundary=temp(wdir / f'{graph}.dbg.pred_boundary'),
        succ=temp(wdir / f'{graph}.dbg.succ'),
        succ_boundary=temp(wdir / f'{graph}.dbg.succ_boundary'),
        rd_succ=temp(wdir / f'{graph}.dbg.rd_succ'),
        row_reduction=temp(rd_cols_dir / 'vector.row_reduction'),
        stage1_done=touch(rd_cols_dir / 'stage1.DONE')
    threads: max_threads
    resources:
        mem_mb=TransformRdStage1Resources(config).get_mem()
    params:
        mem_buffer=TransformRdStage1Resources(config).get_mem_buffer_gib(),
        rd_cols_dir=rd_cols_dir,
        tempdir_opt=utils.temp_dir_config(config),
    log: utils.get_log_path(TRANSFORM_RD_STAGE1_RULE, config)
    shell:
        """
        cat {input.columns_file} | {time_cmd} {metagraph_cmd} transform_anno {verbose_opt} \
            --anno-type row_diff \
            --row-diff-stage 1 \
            -i {input.dbg_graph} \
            --parallel {threads} \
            {count_kmers_opt} \
            {coordinates_opt} \
            {count_width_opt} \
            --mem-cap-gb {params.mem_buffer} \
            -o {output.row_reduction} {params.tempdir_opt} > {log} 2>&1
        """


TRANSFORM_RD_STAGE2_RULE="transform_rd_stage2"
rule transform_rd_stage2:
    input:
        dbg_graph=graph_path,
        columns_file=columns_file,
        column_anno_files=rules.annotate.output.column_anno_files,
        column_count_files=rules.annotate.output.column_count_files,
        column_coord_files=rules.annotate.output.column_coord_files,
        row_reduction=rules.transform_rd_stage1.output.row_reduction,
        pred=rules.transform_rd_stage1.output.pred,
        pred_boundary=rules.transform_rd_stage1.output.pred_boundary,
        succ=rules.transform_rd_stage1.output.succ,
        succ_boundary=rules.transform_rd_stage1.output.succ_boundary,
        rd_succ=rules.transform_rd_stage1.output.rd_succ,
        stage1_done=rules.transform_rd_stage1.output.stage1_done
    output:
        anchors=temp(wdir/f'{graph}.dbg.anchors'),
        rd_cols_done=touch(rd_cols_dir/DONE),
        rd_col_annodbg_files=temp(rd_col_annodbg_paths),
        rd_col_count_files=(temp(rd_col_counts_paths) if with_counts else []),
        rd_col_coord_files=(temp(rd_col_coords_paths) if with_coordinates else []),
    threads: max_threads
    resources:
        mem_mb=TransformRdStage2Resources(config).get_mem(),
    params:
        mem_buffer=TransformRdStage2Resources(config).get_mem_buffer_gib(),
        tempdir_opt=utils.temp_dir_config(config),
    log: utils.get_log_path(TRANSFORM_RD_STAGE2_RULE, config)
    shell:
        """
        cat {input.columns_file} | {time_cmd} {metagraph_cmd} transform_anno {verbose_opt} \
            --anno-type row_diff \
            --row-diff-stage 2 \
            -i {input.dbg_graph} \
            --parallel {threads} \
            {count_kmers_opt} \
            {coordinates_opt} \
            {count_width_opt} \
            --mem-cap-gb {params.mem_buffer} \
            -o {output.rd_cols_done} {params.tempdir_opt} > {log} 2>&1
        """


ANNOTATE_ROW_DIFF_BRWT_RULE="annotate_row_diff_brwt"
rule annotate_row_diff_brwt:
    input:
        rd_succ=rules.transform_rd_stage1.output.rd_succ,
        anchors=rules.transform_rd_stage2.output.anchors,
        rd_cols_done=rules.transform_rd_stage2.output.rd_cols_done,
        rd_col_annodbg_files=rules.transform_rd_stage2.output.rd_col_annodbg_files,
        rd_col_count_files=rules.transform_rd_stage2.output.rd_col_count_files,
        rd_col_coord_files=rules.transform_rd_stage2.output.rd_col_coord_files,
        dbg_graph=graph_path
    output:
        annotations=wdir/f'{graph}.row_diff_brwt.annodbg',
        linkage=temp(wdir / f'{graph}.row_diff_brwt.annodbg.linkage'),
    threads: max_threads
    resources:
        mem_mb=ResourceConfig(ANNOTATE_ROW_DIFF_BRWT_RULE, config).get_mem(),
    params:
        parallel_nodes=config[workflow_configs.BRWT_PARALLEL_NODES],
        tempdir_opt=utils.temp_dir_config(config),
    log: utils.get_log_path(ANNOTATE_ROW_DIFF_BRWT_RULE, config)
    shell:
        r"""
        echo $(find $(dirname {input.rd_cols_done}) -name \*.annodbg)
        find $(dirname {input.rd_cols_done}) -name \*.annodbg | {time_cmd} {metagraph_cmd} transform_anno {verbose_opt} \
            --anno-type row_diff_brwt \
            --greedy \
            --parallel-nodes {params.parallel_nodes} \
            --parallel {threads} \
            -i {input.dbg_graph} \
            -o {output.annotations} {params.tempdir_opt} > {log} 2>&1
        """


RELAX_ROW_DIFF_BRWT_RULE="relax_row_diff_brwt"
rule relax_row_diff_brwt:
    input:
        brwt_annots=rules.annotate_row_diff_brwt.output.annotations,
    output:
        annotations_relaxed=wdir/f'{graph}.relax.row_diff_brwt.annodbg',
    threads: max_threads
    resources:
        mem_mb=ResourceConfig(RELAX_ROW_DIFF_BRWT_RULE, config).get_mem(),
    params:
        relax_arity = config[workflow_configs.BRWT_RELAX_ARITY],
    log: utils.get_log_path(RELAX_ROW_DIFF_BRWT_RULE, config)
    shell:
        """
        {time_cmd} {metagraph_cmd} relax_brwt \
            -o {output.annotations_relaxed} \
            {verbose_opt} \
            --relax-arity {params.relax_arity} \
            --parallel {threads} \
            {input.brwt_annots} > {log} 2>&1
        """


ANNOTATE_ROW_DIFF_INT_BRWT_RULE="annotate_row_diff_int_brwt"
rule annotate_row_diff_int_brwt:
    input:
        rd_succ=rules.transform_rd_stage1.output.rd_succ,
        anchors=rules.transform_rd_stage2.output.anchors,
        rd_cols_done=rules.transform_rd_stage2.output.rd_cols_done,
        rd_col_annodbg_files=rules.transform_rd_stage2.output.rd_col_annodbg_files,
        rd_col_count_files=rules.transform_rd_stage2.output.rd_col_count_files,
        rd_col_coord_files=rules.transform_rd_stage2.output.rd_col_coord_files,
        dbg_graph=graph_path
    output:
        annotations=wdir/f'{graph}.row_diff_int_brwt.annodbg',
        linkage=temp(wdir/f'{graph}.row_diff_int_brwt.annodbg.linkage')
    threads: max_threads
    resources:
        mem_mb=ResourceConfig(ANNOTATE_ROW_DIFF_INT_BRWT_RULE, config).get_mem(),
    params:
        parallel_nodes=config[workflow_configs.BRWT_PARALLEL_NODES],
        tempdir_opt=utils.temp_dir_config(config),
    log: utils.get_log_path(ANNOTATE_ROW_DIFF_INT_BRWT_RULE, config)
    shell:
        r"""
        find $(dirname {input.rd_cols_done}) -name \*.annodbg | {time_cmd} {metagraph_cmd} transform_anno {verbose_opt} \
            --anno-type row_diff_int_brwt \
            --greedy \
            --parallel-nodes {params.parallel_nodes} \
            --parallel {threads} \
            -i {input.dbg_graph} \
            -o {output.annotations} {params.tempdir_opt} > {log} 2>&1
        """


ANNOTATE_ROW_DIFF_INT_DISK_RULE="annotate_row_diff_int_disk"
rule annotate_row_diff_int_disk:
    input:
        rd_succ=rules.transform_rd_stage1.output.rd_succ,
        anchors=rules.transform_rd_stage2.output.anchors,
        rd_cols_done=rules.transform_rd_stage2.output.rd_cols_done,
        rd_col_annodbg_files=rules.transform_rd_stage2.output.rd_col_annodbg_files,
        rd_col_count_files=rules.transform_rd_stage2.output.rd_col_count_files,
        rd_col_coord_files=rules.transform_rd_stage2.output.rd_col_coord_files,
        dbg_graph=graph_path
    output:
        annotations=wdir/f'{graph}.row_diff_int_disk.annodbg',
    threads: max_threads
    resources:
        mem_mb=ResourceConfig(ANNOTATE_ROW_DIFF_INT_DISK_RULE, config).get_mem(),
    params:
        tempdir_opt=utils.temp_dir_config(config),
    log: utils.get_log_path(ANNOTATE_ROW_DIFF_INT_DISK_RULE, config)
    shell:
        r"""
        find $(dirname {input.rd_cols_done}) -name \*.annodbg | {time_cmd} {metagraph_cmd} transform_anno {verbose_opt} \
            --anno-type row_diff_int_disk \
            --parallel {threads} \
            -i {input.dbg_graph} \
            -o {output.annotations} {params.tempdir_opt} > {log} 2>&1
        """


ANNOTATE_ROW_DIFF_BRWT_COORD_RULE="annotate_row_diff_brwt_coord"
rule annotate_row_diff_brwt_coord:
    input:
        rd_succ=rules.transform_rd_stage1.output.rd_succ,
        anchors=rules.transform_rd_stage2.output.anchors,
        rd_cols_done=rules.transform_rd_stage2.output.rd_cols_done,
        rd_col_annodbg_files=rules.transform_rd_stage2.output.rd_col_annodbg_files,
        rd_col_count_files=rules.transform_rd_stage2.output.rd_col_count_files,
        rd_col_coord_files=rules.transform_rd_stage2.output.rd_col_coord_files,
        dbg_graph=graph_path
    output:
        annotations=wdir/f'{graph}.row_diff_brwt_coord.annodbg',
        linkage=temp(wdir/f'{graph}.row_diff_brwt_coord.annodbg.linkage')
    threads: max_threads
    resources:
        mem_mb=ResourceConfig(ANNOTATE_ROW_DIFF_BRWT_COORD_RULE, config).get_mem(),
    params:
        parallel_nodes=config[workflow_configs.BRWT_PARALLEL_NODES],
        tempdir_opt=utils.temp_dir_config(config),
    log: utils.get_log_path(ANNOTATE_ROW_DIFF_BRWT_COORD_RULE, config)
    shell:
        r"""
        find $(dirname {input.rd_cols_done}) -name \*.annodbg | {time_cmd} {metagraph_cmd} transform_anno {verbose_opt} \
            --anno-type row_diff_brwt_coord \
            --greedy \
            --parallel-nodes {params.parallel_nodes} \
            --parallel {threads} \
            -i {input.dbg_graph} \
            -o {output.annotations} {params.tempdir_opt} > {log} 2>&1
        """


ANNOTATE_ROW_DIFF_COORD_RULE="annotate_row_diff_coord"
rule annotate_row_diff_coord:
    input:
        rd_succ=rules.transform_rd_stage1.output.rd_succ,
        anchors=rules.transform_rd_stage2.output.anchors,
        rd_cols_done=rules.transform_rd_stage2.output.rd_cols_done,
        rd_col_annodbg_files=rules.transform_rd_stage2.output.rd_col_annodbg_files,
        rd_col_count_files=rules.transform_rd_stage2.output.rd_col_count_files,
        rd_col_coord_files=rules.transform_rd_stage2.output.rd_col_coord_files,
        dbg_graph=graph_path
    output:
        annotations=wdir/f'{graph}.row_diff_coord.annodbg',
    threads: max_threads
    resources:
        mem_mb=ResourceConfig(ANNOTATE_ROW_DIFF_COORD_RULE, config).get_mem(),
    params:
        tempdir_opt=utils.temp_dir_config(config),
    log: utils.get_log_path(ANNOTATE_ROW_DIFF_COORD_RULE, config)
    shell:
        r"""
        find $(dirname {input.rd_cols_done}) -name \*.annodbg | {time_cmd} {metagraph_cmd} transform_anno {verbose_opt} \
            --anno-type row_diff_coord \
            --parallel {threads} \
            -i {input.dbg_graph} \
            -o {output.annotations} {params.tempdir_opt} > {log} 2>&1
        """


ANNOTATE_ROW_DIFF_DISK_COORD_RULE="annotate_row_diff_disk_coord"
rule annotate_row_diff_disk_coord:
    input:
        rd_succ=rules.transform_rd_stage1.output.rd_succ,
        anchors=rules.transform_rd_stage2.output.anchors,
        rd_cols_done=rules.transform_rd_stage2.output.rd_cols_done,
        rd_col_annodbg_files=rules.transform_rd_stage2.output.rd_col_annodbg_files,
        rd_col_count_files=rules.transform_rd_stage2.output.rd_col_count_files,
        rd_col_coord_files=rules.transform_rd_stage2.output.rd_col_coord_files,
        dbg_graph=graph_path
    output:
        annotations=wdir/f'{graph}.row_diff_disk_coord.annodbg',
    threads: max_threads
    resources:
        mem_mb=ResourceConfig(ANNOTATE_ROW_DIFF_DISK_COORD_RULE, config).get_mem(),
    params:
        tempdir_opt=utils.temp_dir_config(config),
    log: utils.get_log_path(ANNOTATE_ROW_DIFF_DISK_COORD_RULE, config)
    shell:
        r"""
        find $(dirname {input.rd_cols_done}) -name \*.annodbg | {time_cmd} {metagraph_cmd} transform_anno {verbose_opt} \
            --anno-type row_diff_disk_coord \
            --parallel {threads} \
            -i {input.dbg_graph} \
            -o {output.annotations} {params.tempdir_opt} > {log} 2>&1
        """
