name: 'Setup Examples'
description: 'Clone metagraph-examples and optionally link metagraph subdirectory'

inputs:
  example-type:
    description: 'Type of example (subdirectory or ExternalProject)'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Checkout metagraph-examples
      run: git clone https://github.com/ratschlab/metagraph-examples.git metagraph-examples
      shell: bash

    - name: Setup metagraph symlink for subdirectory
      if: inputs.example-type == 'subdirectory'
      run: |
        cd metagraph-examples/subdirectory
        rm -rf metagraph
        ln -s "${GITHUB_WORKSPACE}" metagraph
      shell: bash
