name: 'Run Integration Tests'
description: 'Run metagraph integration tests'

inputs:
  working-directory:
    description: 'Working directory containing the build'
    required: false
    default: 'metagraph/build'
  max-attempts:
    description: 'Maximum number of retry attempts'
    required: true
  ld-library-path:
    description: 'Additional LD_LIBRARY_PATH entries'
    required: false
  target-arch:
    description: 'Target architecture (for macOS: arm64 or x86_64)'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Run integration tests
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 1000
        max_attempts: ${{ inputs.max-attempts }}
        retry_on: error
        command: |
          ${{ inputs.ld-library-path && format('export LD_LIBRARY_PATH="{0}:$LD_LIBRARY_PATH"', inputs.ld-library-path) || '' }}
          cd ${{ inputs.working-directory }}
          chmod +x test_venv/bin/python
          ${{ inputs.target-arch && format('arch -{0} ', inputs.target-arch) || '' }}./test_venv/bin/python ../integration_tests/main.py
