name: 'Run Integration Tests'
description: 'Run metagraph integration tests'

inputs:
  working-directory:
    description: 'Working directory containing the build'
    required: false
    default: 'metagraph/build'
  use-retry:
    description: 'Whether to use retry mechanism'
    required: false
    default: 'false'
  ld-library-path:
    description: 'Additional LD_LIBRARY_PATH entries'
    required: false
    default: ''

runs:
  using: 'composite'
  defaults:
    run:
      shell: bash
  steps:
    - name: Run integration tests (with retry)
      if: inputs.use-retry == 'true'
      uses: nick-fields/retry@v2
      with:
        timeout_minutes: 1000
        max_attempts: 5
        retry_on: error
        command: |
          ${LD_LIBRARY_PATH:+export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$LD_LIBRARY_PATH"}
          cd ${{ inputs.working-directory }}
          chmod +x test_venv/bin/python
          ./test_venv/bin/python ../integration_tests/main.py
      env:
        LD_LIBRARY_PATH: ${{ inputs.ld-library-path }}

    - name: Run integration tests (no retry)
      if: inputs.use-retry != 'true'
      run: |
        ${LD_LIBRARY_PATH:+export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$LD_LIBRARY_PATH"}
        cd ${{ inputs.working-directory }}
        chmod +x test_venv/bin/python
        ./test_venv/bin/python ../integration_tests/main.py
      env:
        LD_LIBRARY_PATH: ${{ inputs.ld-library-path }}
