name: 'Install Linux Dependencies'
description: 'Install dependencies for building and testing MetaGraph on Linux'

inputs:
  compiler:
    description: 'Compiler to install (e.g., g++-13)'
    required: true
  cc:
    description: 'C compiler name (e.g., gcc-13)'
    required: true
  cxx:
    description: 'C++ compiler name (e.g., g++-13)'
    required: true
  build_static:
    description: 'Whether building static binaries (ON/OFF)'
    required: true
  job-type:
    description: 'Job type: build, unit-tests, integration-tests, or examples'
    required: true

runs:
  using: "composite"
  steps:
    - name: install build dependencies
      shell: bash
      run: |
        sudo apt-get update

        # If clang, use the default version. Otherwise the compiler install with apt-get.
        if [[ "${{ inputs.compiler }}" != "clang" ]]; then
            sudo apt-get install -y ${{ inputs.compiler }}
        fi

        sudo apt-get install -y cmake make libbz2-dev libjemalloc-dev libboost-all-dev libdeflate-dev liblzma-dev libzstd-dev

        if [ "${{ inputs.build_static }}" = "ON" ]; then
          sudo apt-get install -y libcurl4-openssl-dev
        fi

        echo "CC=$(which ${{ inputs.cc }})" >> $GITHUB_ENV
        echo "CXX=$(which ${{ inputs.cxx }})" >> $GITHUB_ENV

    - name: Install Python packages for tests
      if: inputs.job-type == 'integration-tests'
      shell: bash
      run: |
        pip3 install parameterized
        sudo apt-get install python3-venv
