#!/usr/bin/env python3
import sys
import os


def exec_file_merging(gfa_main_filepath: str, gfa_path_filepaths: []):
    gfa_file = open(gfa_main_filepath, "a")
    next_P_index = 0
    for path_file in gfa_path_filepaths:
        file_reader = open(path_file, 'r')
        lines = file_reader.readlines()
        for line in lines:
            gfa_file.write("{}\t{}".format(next_P_index, line.split("\t",1)[1]))
            next_P_index += 1

def main():
    if len(sys.argv) < 2:
        print("Usage: {} <assembled.gfa> [<align1.path.gfa>] [<align2.path.gfa>] ..".format(sys.argv[0]))
        exit(1)
    if not sys.argv[1].endswith(".gfa"):
        print("Error: First arg must have a '.gfa' extension (file generated by assemble cmd)")
        exit(1)

    gfa_files_to_merge = []
    if len(sys.argv) > 2:
        for file in sys.argv[2:]:
            if not file.endswith(".path.gfa"):
                print("Error: Excepting the first arg, all the others must have a '.path.gfa' extension (file generated by align cmd)")
                exit(1)
        gfa_files_to_merge = sys.argv[2:]
    else:
        print("Searching for '.path.gfa' files in the same directory..")
        dir = os.path.dirname(sys.argv[1])
        for file in os.listdir(dir):
            if file.endswith(".path.gfa"):
                print("Found: " + file)
                gfa_files_to_merge.append(os.path.join(dir, file))

    exec_file_merging(sys.argv[1], gfa_files_to_merge)
    print("The merging has been successfully finished! Everything is appended to '{}'".format(sys.argv[1]))


if __name__ == '__main__':
    main()
