"""Golden digests of the metagraph.traverse library's unbudgeted outputs (not a test module
itself): every public operation, with a fixed set of arguments, reduced to a stable digest
per (graphlet, operation), and the MCP tools over a store of the same graphlets.

The speed-ups and the local-limits charge points must leave every unbudgeted output byte
for byte the same (DESIGN §21): test_traverse_speedups.py compares the digests of the
committed real and review3 fixtures with data/traverse/golden/committed.json.gz, the
reference digests, and test_traverse_stage_l.py takes the same digests with an unlimited
LocalBudget (local limits must not change an answer either). The command line records
digests with any library version; an intended output change, or new real/review3
fixtures, means recording them again (and saying why in the commit):

    python3 traverse_golden.py --lib /path/to/api/python --out digests.json[.gz] [INPUT ...]
    python3 traverse_golden.py --diff a.json b.json

INPUT: files or directories of *.graphlet.json[.gz] responses or recorded requests
({meta, request, response}); none: the committed real/ and review3/ fixtures. A digest is
the sha256 of the canonical JSON of the result (dataclasses by field, sets sorted, labels
as {name, ref}); an operation that raises records 'ERR:<type>'.
"""

import argparse
import dataclasses
import glob
import gzip
import hashlib
import json
import math
import os
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(HERE, 'data', 'traverse')
GOLDEN_DIR = os.path.join(DATA, 'golden')
# the committed inputs of the golden gate: recorded server responses that no generator
# rewrites (the CLI fixtures under documents/ are regenerated by graphlet_fixtures.py)
GOLDEN_GLOBS = ('real/*/*.graphlet.json.gz', 'review3/*.graphlet.json')
LABEL_CAP = 24          # label loops per graphlet (routes, label_walks, label by name)
ADDITIVE_FIELDS = ('local_stop',)
WALK_CAP = 4            # walks whose spelling, profile and continuation are digested


# ------------------------------------------------------------------ canonical form

def canonical(x, depth=0):
    if depth > 40:
        return '<deep>'
    if x is None or isinstance(x, (bool, int, str)):
        return x
    if isinstance(x, float):
        return repr(x) if not math.isfinite(x) else x
    if isinstance(x, (bytes, bytearray)):
        return hashlib.sha256(bytes(x)).hexdigest()
    if isinstance(x, dict):
        out = {str(k): canonical(v, depth + 1) for k, v in x.items()}
        # NextRequest and friends: a dict that carries attributes beside its items
        extra = {k: canonical(v, depth + 1) for k, v in getattr(x, '__dict__', {}).items()
                 if not k.startswith('_')}
        if extra:
            out = {'_items': out, '_attrs': extra}
        return out
    if isinstance(x, (list, tuple)):
        return [canonical(v, depth + 1) for v in x]
    if isinstance(x, (set, frozenset)):
        return sorted((canonical(v, depth + 1) for v in x),
                      key=lambda v: json.dumps(v, sort_keys=True, default=str))
    t = type(x).__name__
    if t == 'array':
        return list(x)
    if t == 'Label':
        return {'name': x.name, 'ref': x.ref}
    if t == 'Path':
        return {'_t': 'Path', 'id': x.id, 'leaf': x.leaf, 'length_bp': x.length_bp}
    if t == 'GraphletView':
        return {'_t': 'GraphletView', 'spec': canonical(x.view_spec(), depth + 1),
                'segments': canonical(x.segments, depth + 1),
                'path_ids': canonical(x.path_ids, depth + 1)}
    if dataclasses.is_dataclass(x) and not isinstance(x, type):
        # Comparison.local_stop (local limits) is additive: None on every answer that did not
        # stop, so the digests of a library without it stay comparable
        return {'_t': t, 'v': {f.name: canonical(getattr(x, f.name, None), depth + 1)
                               for f in dataclasses.fields(x)
                               if f.compare is not False and f.name not in ('cache', 'arm')
                               and not (f.name in ADDITIVE_FIELDS
                                        and getattr(x, f.name, None) is None)}}
    return '<%s>' % t


def digest(x):
    return hashlib.sha256(json.dumps(canonical(x), sort_keys=True, default=str,
                                     ensure_ascii=False).encode('utf-8')).hexdigest()[:20]


# ------------------------------------------------------------------ inputs

def read_json(path):
    if path.endswith('.gz'):
        with gzip.open(path, 'rt', encoding='utf-8') as f:
            return json.load(f)
    with open(path, encoding='utf-8') as f:
        return json.load(f)


# the real cells that asked for record coordinates (feature level 6): opt-in retrievals, gated by
# the coordinates golden file (golden/coordinates.json.gz) with the snapshots of data/traverse/coords;
# the committed gate stays the opt-out one it was recorded as
COORDINATE_CELLS = '__trace_coords'


def golden_files():
    out = []
    for g in GOLDEN_GLOBS:
        out += [p for p in glob.glob(os.path.join(DATA, g))
                if COORDINATE_CELLS not in os.path.basename(p)]
    return sorted(out)


def coordinate_files():
    """The inputs of the coordinates golden file: the snapshots and the real coordinate cells."""
    return sorted(glob.glob(os.path.join(DATA, 'coords', '*.graphlet.json.gz'))
                  + [p for p in glob.glob(os.path.join(DATA, GOLDEN_GLOBS[0]))
                     if COORDINATE_CELLS in os.path.basename(p)])


def items_of(paths, base=None):
    """[(key, result, response)] of every result with a graphlet."""
    files = []
    for p in paths:
        if os.path.isdir(p):
            for pat in ('*.json', '*.json.gz'):
                files += glob.glob(os.path.join(p, pat))
        else:
            files.append(p)
    out = []
    for f in sorted(set(files)):
        try:
            d = read_json(f)
        except (OSError, ValueError):
            continue
        if not isinstance(d, dict):
            continue
        resp = d['response'] if isinstance(d.get('response'), dict) else d
        for i, r in enumerate(resp.get('results') or []):
            if isinstance(r, dict) and isinstance(r.get('graphlet'), str):
                key = '%s#%d' % (os.path.relpath(f, base) if base else os.path.basename(f), i)
                out.append((key, r, resp))
    return out


# ------------------------------------------------------------------ operations

def _call(out, name, fn):
    try:
        out[name] = digest(fn())
    except Exception as e:    # an operation that does not apply records its error type
        out[name] = 'ERR:%s' % type(e).__name__


def op_digests(T, g, budget=None):
    """{op: digest} of every public operation on |g| (the library module |T| =
    metagraph.traverse). |budget|: None, or a callable returning the keyword arguments
    each call gets (local limits: {'budget': LocalBudget()})."""
    kw = budget or (lambda: {})
    out = {}
    from importlib import import_module
    ops = import_module(T.__name__ + '.ops')
    _call(out, 'dump', lambda: g.dump(**kw()))
    _call(out, 'dump_body', lambda: g.dump(envelope=False, **kw()))
    _call(out, 'to_json', lambda: g.to_json(**kw()))
    _call(out, 'to_fasta', lambda: g.to_fasta(**kw()))
    _call(out, 'to_fasta_walk', lambda: g.to_fasta(orientation='walk', with_seed=False,
                                                   width=7, **kw()))
    _call(out, 'to_gfa', lambda: g.to_gfa(**kw()))
    _call(out, 'to_gfa_noseed', lambda: g.to_gfa(with_seed=False, **kw()))
    _call(out, 'summary', lambda: g.summary(**kw()))
    _call(out, 'summary_300', lambda: g.summary(max_bytes=300, **kw()))
    _call(out, 'label_summary', lambda: g.label_summary(**kw()))
    _call(out, 'claims', lambda: g.claims(strict=False, **kw()))
    _call(out, 'claims_strict', lambda: g.claims(**kw()))
    _call(out, 'check_rules', lambda: g.check_rules())
    sel = [{'id': 0}] if g.labels else None
    if sel:
        _call(out, 'claims_label0', lambda: g.claims(labels=sel, strict=False, **kw()))
        _call(out, 'subgraph', lambda: g.subgraph(sel, **kw()))
        _call(out, 'subgraph_all', lambda: g.subgraph([{'id': i} for i in range(
            min(2, len(g.labels)))], mode='all', **kw()))

        def view_ops():
            v = g.subgraph(sel, **kw())
            return [v.summary(), [v.walks(s, **kw()) for s in v.arms()],
                    v.claims(strict=False, **kw()), v.to_fasta(**kw()), v.dump(**kw())]
        _call(out, 'view_ops', view_ops)
    # label lookups by name and by ref
    names = {}
    for l in g.labels:
        names[l.name] = names.get(l.name, 0) + 1
    picks = g.labels[:LABEL_CAP]
    _call(out, 'label_lookup', lambda: [
        [_safe(lambda: g.label(l.name)), _safe(lambda: g.label({'name': l.name})),
         _safe(lambda: g.label({'ref': l.ref})), _safe(lambda: g.label(l.ref))]
        for l in picks])
    _call(out, 'label_unknown', lambda: _safe(lambda: g.label('no such label ☃')))
    for side, a in g.arms.items():
        p = side[0]
        depth = a.complete_to_bp
        _call(out, p + ':claims_cut', lambda: g.claims(side, at_most_bp=depth // 2,
                                                       strict=False, **kw()))
        for by in ('support', 'length', 'loss', 'id'):
            _call(out, p + ':walks_' + by, lambda: g.walks(side, by=by, **kw()))
            _call(out, p + ':rank_' + by, lambda: ops.rank_walks(g, side, by=by, **kw()))
        _call(out, p + ':walks_top3', lambda: g.walks(side, top=3, **kw()))
        _call(out, p + ':walks_min', lambda: g.walks(side, min_bp=depth // 2, top=5, **kw()))
        if sel:
            _call(out, p + ':walks_label', lambda: g.walks(side, labels=sel, **kw()))
            _call(out, p + ':walks_label_rc', lambda: g.walks(side, labels=sel,
                                                              route_consistent=False, **kw()))
        n_paths = len(T.derive.paths(a)) if hasattr(T, 'derive') else None
        if n_paths is None:
            from importlib import import_module as _im
            n_paths = len(_im(T.__name__ + '.derive').paths(a))
        ids = list(range(min(WALK_CAP, n_paths))) + ([n_paths - 1] if n_paths > WALK_CAP
                                                     else [])
        _call(out, p + ':walks_at', lambda: ops.walks_at(g, side, ids, with_claims=True,
                                                         **kw()))
        _call(out, p + ':splits', lambda: g.splits(side, **kw()))
        _call(out, p + ':splits_2', lambda: g.splits(side, min_labels_before=2, **kw()))
        for w in ids:
            q = '%s:w%d:' % (p, w)
            _call(out, q + 'spell', lambda: [g.spell(side, w, **kw()),
                                             g.spell(side, w, 'walk', True, **kw()),
                                             g.spell(side, w, with_seed=True, **kw())])
            _call(out, q + 'profile', lambda: g.support_profile(side, w, **kw()))
            _call(out, q + 'profile_route', lambda: g.support_profile(side, w, 'route', **kw()))
            _call(out, q + 'changes', lambda: g.support_changes(side, w, **kw()))
            _call(out, q + 'continuation', lambda: g.continuation(side, w, **kw()))
            _call(out, q + 'next_request', lambda: g.next_request(side, [w], **kw()))
            _call(out, q + 'next_request_keep', lambda: g.next_request(
                side, [w], bp=50, reduce_budget=False, reset_branches=True, **kw()))
        _call(out, p + ':next_requests', lambda: g.next_requests(side, ids, **kw()))
        _call(out, p + ':next_request_all', lambda: g.next_request(side, ids, **kw()))
        for l in picks:
            q = '%s:l%d:' % (p, l.id)
            _call(out, q + 'routes', lambda: g.routes({'id': l.id}, side, **kw()))
            _call(out, q + 'routes_spell', lambda: g.routes({'id': l.id}, side, spell=True,
                                                            **kw()))
            _call(out, q + 'label_walks', lambda: g.label_walks({'id': l.id}, side, **kw()))
        for pos in sorted({0, depth // 3, depth // 2, max(0, depth - 1)}):
            _call(out, '%s:alive%d' % (p, pos), lambda: [
                ops.alive_at(g, side, s.id, pos) for s in a.segments
                if s.from_bp <= pos < s.end_bp])
    for l in picks[:4]:
        _call(out, 'l%d:label_walks_both' % l.id, lambda: g.label_walks({'id': l.id}, **kw()))
    return out


def _safe(fn):
    try:
        return fn()
    except Exception as e:
        return 'ERR:%s' % type(e).__name__


def compare_digests(a, b, budget=None):
    kw = budget or (lambda: {})
    out = {}
    for mode in ('claims', 'walks', 'labels', 'prefix_subset'):
        _call(out, 'compare_' + mode, lambda: a.compare(b, mode=mode, **kw()).as_dict())
        _call(out, 'compare_full_' + mode, lambda: a.compare(b, mode=mode, **kw()))
        if a.labels:
            _call(out, 'compare_label_' + mode, lambda: a.compare(
                b, mode=mode, labels=[{'ref': a.labels[0].ref}], **kw()).as_dict())
    return out


# ------------------------------------------------------------------ tools

def _norm(x, handles):
    """Handles (random) and cursors (bound to them) replaced by stable placeholders."""
    if isinstance(x, dict):
        return {k: ('<cursor>' if k == 'next_cursor' else _norm(v, handles))
                for k, v in x.items()}
    if isinstance(x, list):
        return [_norm(v, handles) for v in x]
    if isinstance(x, str):
        for h, name in handles.items():
            if h in x:
                x = x.replace(h, name)
        # a handle made during the run (graphlet_subtrie)
        return _HANDLE.sub('<new>', x)
    return x


_HANDLE = __import__('re').compile(r'g_[0-9a-f]{12}')


def tool_digests(T, items, tool_kw=None):
    """{'<key>:<tool>': digest} of the MCP tools over a fresh store holding |items|
    (see items_of). |tool_kw|: extra keyword arguments for GraphletTools."""
    from importlib import import_module
    mcp = import_module(T.__name__ + '.mcp_tools')
    out = {}
    with tempfile.TemporaryDirectory() as d:
        store = T.GraphletStore(os.path.join(d, 'spool'))
        tools = mcp.GraphletTools(store, secret=b'k' * 32, export_dir=os.path.join(d, 'x'),
                                  **(tool_kw or {}))
        handles = {}
        keyed = []
        for k, (key, r, resp) in enumerate(items):
            g = T.from_response(r, resp)
            h = store.put_parsed(g, r['graphlet'], {'seeds': []})
            handles[h] = '<h%d>' % k
            keyed.append((key, h, g))

        def rec(key, name, res):
            out['%s:%s' % (key, name)] = digest(_norm(res, handles))

        def page_all(fn, **kw):
            pages, cur = [], None
            for _ in range(200):
                res = fn(cursor=cur, **kw)
                pages.append(res)
                cur = res.get('next_cursor') if isinstance(res, dict) else None
                if not cur:
                    break
            return pages

        for key, h, g in keyed:
            sides = list(g.arms)
            rec(key, 'summary', tools.graphlet_summary(h))
            rec(key, 'summary_lim', page_all(tools.graphlet_summary, handle=h,
                                             detail='limitations'))
            rec(key, 'labels', page_all(tools.graphlet_labels, handle=h, max_bytes=4096))
            if g.labels:
                rec(key, 'labels_name', page_all(tools.graphlet_labels, handle=h,
                                                 name={'ref': g.labels[0].ref}))
                rec(key, 'subtrie', _norm(tools.graphlet_subtrie(
                    h, [{'ref': g.labels[0].ref}]), handles))
            for s in sides:
                rec(key, s + ':walks', page_all(tools.graphlet_walks, handle=h, arm=s,
                                                spell='tail', max_bytes=8192))
                rec(key, s + ':walks_id', page_all(tools.graphlet_walks, handle=h, arm=s,
                                                   rank='id', n=50))
                rec(key, s + ':walk0', page_all(tools.graphlet_walk, handle=h, arm=s, walk=0))
                rec(key, s + ':support0', page_all(tools.graphlet_support, handle=h, arm=s,
                                                   walk=0))
                rec(key, s + ':splits', page_all(tools.graphlet_splits, handle=h, arm=s,
                                                 min_labels_before=0))
                rec(key, s + ':claims', page_all(tools.graphlet_claims, handle=h, arm=s,
                                                 max_bytes=8192))
                rec(key, s + ':claims_rc', page_all(tools.graphlet_claims, handle=h, arm=s,
                                                    route_consistent=False, max_bytes=8192))
                rec(key, s + ':sequence', tools.graphlet_sequence(h, s, walk=0))
                rec(key, s + ':cont', tools.traverse_continue(h, s, 0, execute=False))
            for fmt in ('fasta', 'gfa', 'json', 'mgt'):
                res = tools.graphlet_export(h, format=fmt, path='e.' + fmt)
                body = None
                if isinstance(res, dict) and 'path' in res:
                    with open(res['path'], 'rb') as f:
                        body = hashlib.sha256(f.read()).hexdigest()
                    res = dict(res, path=os.path.basename(res['path']))
                rec(key, 'export_' + fmt, [res, body])
            res = tools.graphlet_save(h, 's.mgt')
            if isinstance(res, dict) and 'path' in res:
                with open(res['path'], 'rb') as f:
                    body = hashlib.sha256(f.read()).hexdigest()
                res = dict(res, path=os.path.basename(res['path']))
                rec(key, 'save', [res, body])
        for (ka, ha, ga), (kb, hb, gb) in _pairs(keyed):
            for mode in ('claims', 'walks', 'labels', 'prefix_subset'):
                rec(ka + '|' + kb, 'compare_' + mode,
                    page_all(tools.graphlet_compare, a=ha, b=hb, mode=mode, max_bytes=8192))
    return out


def _pairs(keyed):
    """Consecutive graphlets of the same seed (the same S line)."""
    by = {}
    for x in keyed:
        by.setdefault(x[2].seed.sequence, []).append(x)
    out = []
    for xs in by.values():
        out += list(zip(xs, xs[1:]))
    return out


def all_digests(T, items, budget=None, tools=True):
    out = {}
    graphs = []
    for key, r, resp in items:
        try:
            g = T.from_response(r, resp)
        except Exception as e:
            out[key + ':parse'] = 'ERR:%s' % type(e).__name__
            continue
        graphs.append((key, g, r, resp))
        for op, d in op_digests(T, g, budget).items():
            out['%s:%s' % (key, op)] = d
    by = {}
    for key, g, r, resp in graphs:
        by.setdefault(g.seed.sequence, []).append((key, r, resp))
    for xs in by.values():
        for (ka, ra, pa), (kb, rb, pb) in zip(xs, xs[1:]):
            # fresh models: a comparison must not depend on what earlier calls cached
            a, b = T.from_response(ra, pa), T.from_response(rb, pb)
            for op, d in compare_digests(a, b, budget).items():
                out['%s|%s:%s' % (ka, kb, op)] = d
    if tools:
        out.update({'tool:' + k: v for k, v in tool_digests(T, items).items()})
    return out


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split('\n\n')[0])
    ap.add_argument('inputs', nargs='*')
    ap.add_argument('--lib', default=os.path.dirname(HERE))
    ap.add_argument('--out')
    ap.add_argument('--no-tools', action='store_true')
    ap.add_argument('--diff', nargs=2)
    args = ap.parse_args(argv)
    if args.diff:
        a, b = (read_json(p) for p in args.diff)
        bad = sorted(k for k in set(a) | set(b) if a.get(k) != b.get(k))
        for k in bad[:200]:
            print('%s: %s -> %s' % (k, a.get(k), b.get(k)))
        print('%d keys, %d differ' % (len(set(a) | set(b)), len(bad)))
        return 1 if bad else 0
    sys.dont_write_bytecode = True
    sys.path.insert(0, os.path.abspath(args.lib))
    import metagraph.traverse as T
    items = items_of(args.inputs or golden_files(), base=None if args.inputs else DATA)
    out = all_digests(T, items, tools=not args.no_tools)
    text = json.dumps(out, indent=0, sort_keys=True)
    if args.out and args.out.endswith('.gz'):
        # mtime 0: the same digests make the same file
        with gzip.GzipFile(args.out, 'wb', mtime=0) as f:
            f.write(text.encode())
    elif args.out:
        with open(args.out, 'w') as f:
            f.write(text + '\n')
    else:
        print(text)
    print('%d graphlets, %d digests (%s)' % (len(items), len(out), T.__file__), file=sys.stderr)
    return 0


if __name__ == '__main__':
    sys.exit(main())
