"""Shared helpers of the metagraph.traverse tests (not a test module itself)."""

import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
API = os.path.dirname(HERE)
if API not in sys.path:
    sys.path.insert(0, API)

DATA = os.path.join(HERE, 'data', 'traverse')
DOCS = os.path.join(DATA, 'documents')
COMPARE = os.path.join(DOCS, 'compare')

# the whole-document fixtures (§2.7) and what each one exercises. Most are generated by
# the CLI from tiny indexes (scripts/traversal/graphlet_fixtures.py --from-cli, which also
# checks that each still shows its situation); HAND_MADE are written by hand because the
# CLI cannot produce them (a Q record, an unknown counter, the §5.1 claims oracle)
DOCUMENTS = {
    'linear': 'both arms, quorum 2: a minority end at each fork with its V refusal (a '
              'zero-length Rm run at the right seed boundary), a dropped seed label (X)',
    'fork': 'both arms split; the radius (10) is below k (15), so both continuations '
            'cross into the seed',
    'merge': 'column labels through two SNP bubbles (merge): partitions '
             '(labels_via_parent), ambiguous splits with an m closure at each merge, b.fa '
             'through two non-first-parent merges (R.route_bp != T.route_bp), continuations '
             'contained in the flank',
    'switch_chain': 'A -> B -> {C, D}: a silent Lw end inside a segment and one at an '
                    'ambiguous split whose switches sit on the children',
    'annotate': 'annotate mode (merge): P runs, cut lists (cap 2), merges with one empty '
                'partition per parent, contained continuations on both arms',
    'ambiguous_split': 'canonical graph: an ambiguous split with disjoint child sets after a '
                       'switch (right); a followed-hairpin divergence with overlapping child '
                       'sets (left)',
    'reentry': 'A -> B -> A inside one segment: G.end * by the chronological rule',
    'same_name': 'annotate: two headers named ACC1 from different columns (an L line '
                 'ending in a space)',
    'quorum': 'quorum 2: refused minority successors (V), an ambiguous split, two '
              'label_lost ends at one position whose branches (1 and 0) differ only through '
              'a refused successor',
    'caps': 'max_steps truncation, branch events cut at 1, sequences false, a loss_budget '
            'end, a blocked edge_reuse successor, revisits at another distance',
    'no_bins': 'annotate, both arms, max_steps 1 tripping on the left arm at depth 0: the '
               'right arm stopped before its first level and has no B record',
    'clipped_merge': 'the clipped-merge evidence case of §5.1 with its expected claims',
    'limits': 'truncated arm (max_steps), a zero-length merged leaf censored, cut branch '
              'events, sequences false, a loss_budget end, blocked and revisit events, '
              'typed K values, a Q record, an unknown counter',
}
HAND_MADE = ('clipped_merge', 'limits')


REPO = os.path.dirname(os.path.dirname(API))
FIXTURE_SCRIPT = os.path.join(REPO, 'scripts', 'traversal', 'graphlet_fixtures.py')


def fixture_script():
    """scripts/traversal/graphlet_fixtures.py as a module: the definitions of the CLI
    fixtures' indexes (their FASTA records) live there."""
    import importlib.util
    spec = importlib.util.spec_from_file_location('graphlet_fixtures', FIXTURE_SCRIPT)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def cli_record(index, header):
    """The sequence of FASTA record |header| of CLI fixture index |index|."""
    G = fixture_script()
    spec = G.INDEXES[index]
    blocks = G.blocks_of(spec)
    for records in spec['files'].values():
        for h, parts in records:
            if h == header:
                return G.assemble(parts, blocks)
    raise KeyError(header)


def read(path):
    with open(path, 'r', encoding='utf-8', newline='') as f:
        return f.read()


def doc_text(name):
    return read(os.path.join(DOCS, name + '.mgt'))


def doc_json(name, kind):
    with open(os.path.join(DOCS, '%s.%s.json' % (name, kind)), encoding='utf-8') as f:
        return json.load(f)


def compare_text(name):
    return read(os.path.join(COMPARE, name + '.mgt'))


def graphlet(name):
    """The fixture as a client sees it: from_response() over its detail graphlet
    response (envelope attached)."""
    from metagraph.traverse import from_response
    resp = doc_json(name, 'graphlet')
    return from_response(resp['results'][0], resp)


def body(name):
    from metagraph.traverse import parse
    return parse(doc_text(name))


def json_diff(a, b, path=''):
    """Human-readable differences between two JSON values (for assertion messages)."""
    out = []
    if isinstance(a, dict) and isinstance(b, dict):
        for k in sorted(set(a) | set(b)):
            if k not in a:
                out.append('%s/%s missing' % (path, k))
            elif k not in b:
                out.append('%s/%s extra' % (path, k))
            else:
                out.extend(json_diff(a[k], b[k], '%s/%s' % (path, k)))
    elif isinstance(a, list) and isinstance(b, list):
        if len(a) != len(b):
            out.append('%s: length %d vs %d' % (path, len(a), len(b)))
        else:
            for i, (x, y) in enumerate(zip(a, b)):
                out.extend(json_diff(x, y, '%s/%d' % (path, i)))
    elif a != b:
        out.append('%s: %r vs %r' % (path, a, b))
    return out
