name: 'Setup ccache'
description: 'Configure and cache ccache for build acceleration'

inputs:
  build-type:
    description: 'CMake build type (Debug or Release)'
    required: true
  alphabet:
    description: 'Alphabet type (DNA or Protein)'
    required: true
  build-static:
    description: 'Build static binaries (ON or OFF)'
    required: false
    default: 'OFF'
  with-avx:
    description: 'Enable AVX instructions (ON or OFF)'
    required: false
    default: 'ON'
  target-arch:
    description: 'Target architecture (arm64 or x86_64, macOS only)'
    required: false
    default: 'arm64'
  job-type:
    description: 'Job type (Build, ExternalProject, or subdirectory)'
    required: false
    default: 'Build'

runs:
  using: 'composite'
  steps:
    - name: Install ccache
      shell: ${{ runner.os == 'macOS' && format('arch -{0} /bin/bash -e {{0}}', inputs.target-arch) || 'bash' }}
      run: |
        if [[ "${{ runner.os }}" == "macOS" ]]; then
          brew install ccache
        else
          sudo apt-get install -y ccache
        fi

    - name: Cache ccache
      uses: actions/cache@v3
      with:
        path: ${{ runner.os == 'macOS' && '~/Library/Caches/ccache' || '~/.cache/ccache' }}
        key: ccache-${{ runner.os }}-${{ inputs.job-type }}-${{ inputs.build-type }}-${{ inputs.alphabet }}-${{ inputs.target-arch }}-${{ inputs.build-static }}-${{ inputs.with-avx }}

    - name: Setup ccache
      shell: bash
      run: |
        ccache --set-config=max_size=2G
        ccache --set-config=compression=true
        ccache --zero-stats
