[tox]
; could add some more environments in the future (the package needs Python >= 3.10)
envlist = py310, py311, py312, py313, flake8

[travis]
python =
    3.13: py313
    3.12: py312
    3.11: py311
    3.10: py310

[testenv:flake8]
basepython = python
deps = flake8
commands = flake8 metagraph

[testenv]
setenv =
    PYTHONPATH = {toxinidir}

deps =
    -r{toxinidir}/requirements_dev.txt
commands =
    pip install -U pip
    py.test --basetemp={envtmpdir}
