name: Version AutoTag

on:
  push:
    paths:
    - package.json
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: Jaliborc/action-general-autotag@1.0.1
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        source_file: "package.json"
        extraction_regex: "\\s*\"version\"s*:\\s*\"([\\d\\.]+)\""
        tag_format: "v{version}"
        tag_message: "New version"

